services:
  - type: web
    name: microsoft-jobs-tracker
    env: node
    plan: free
    buildCommand: "cd client && npm install && npm run build && cd ../server && npm install"
    startCommand: "cd server && node index.js"
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: RENDER_EXTERNAL_URL
        value: https://microsoft-jobs-tracker.onrender.com
      - key: VAPID_PUBLIC_KEY
        value: BEUu3MqV69o5YBCgKmrgKMLfEAcgPB-wHOu72_-wo3wT8_WD7kvpRNWfczC3f3-P05cd910raPrBavXXZfA6KI4
      - key: VAPID_PRIVATE_KEY
        value: Oi9AX1PLHFuAO5rhkjlYBmUwWzic13qdcJ2ij2CeSaw
      - key: VAPID_EMAIL
        value: mailto:admin@microsoft-jobs-tracker.com
